services:
    nginx_reverse_proxy:
        build:
            context: ../docker_images/nginx_reverse_proxy/
            dockerfile: Dockerfile
        ports:
            - 80:80
        depends_on:
            - frontend_html_js_css
            - backend_qxorm
        networks:
            - compose_qxorm_with_mongodb_frontnet

    frontend_html_js_css:
        hostname: frontend_html_js_css
        restart: on-failure
        build:
            context: ../docker_images/frontend_html_js_css/
            dockerfile: Dockerfile
        networks:
            - compose_qxorm_with_mongodb_frontnet
        expose:
            - 80
        volumes:
            - type: bind
              source: ../docker_images/frontend_html_js_css/src/
              target: /usr/share/nginx/html/

    backend_qxorm:
        hostname: backend_qxorm
        restart: on-failure
        build:
            context: ../docker_images/backend_qxorm/
            dockerfile: Dockerfile
            target: dev
        depends_on:
            - db_mongodb
        networks:
            - compose_qxorm_with_mongodb_frontnet
            - compose_qxorm_with_mongodb_backnet
        volumes:
            - compose_qxorm_backend_src:/home/qxorm
        expose:
            - 9642
            - 9643
        environment:
            - QX_DB=MongoDB

    db_mongodb:
        hostname: db_mongodb
        restart: on-failure
        build:
            context: ../docker_images/db_mongodb/
            dockerfile: Dockerfile
        networks:
            - compose_qxorm_with_mongodb_backnet
        volumes:
            - compose_qxorm_mongodb_db_data:/data/db
        expose:
            - 27017

volumes:
    compose_qxorm_mongodb_db_data:
    compose_qxorm_backend_src:

networks:
    compose_qxorm_with_mongodb_backnet:
    compose_qxorm_with_mongodb_frontnet:
